### ISSUE TITLE
Error when using role `:ref:`

### ISSUE THREAD

**Issue by diogo-rossi** [sphinx-notes/comboroles#2]
Using composite roles with `:ref:` gives an error in sphinx
```
ERROR: no such role: ref
```

## To reproduce:
In Sphinx, make the following heading declaration:
```reST
.. _somestuff:

My section
==========
```

This works ok:
```reST
Have a look at :ref:`somestuff`
```
But when using the composite role in `conf.py`:

```python
comboroles_roles = {
    "literal_ref": ["literal", "ref"],
}
```
This gives the error:
```reST
Have a look at :literal_ref:`somestuff`
```
```sh
ERROR: no such role: ref
```

#### OBS

I already made a workaround using [this approach](https://sphinx.silverrainz.me/comboroles/usage.html#works-with-other-extensions) but opened this issue following [this recomendation](https://sphinx.silverrainz.me/comboroles/usage.html#limitation). Thanks for this great extension!

**Comment by SilverRainZ** [comment]
Hello, What's the version of the extension? ~~It should be fixed in v1.0.0.a1~~

**Comment by SilverRainZ** [comment]
I have reproduced it, thanks for the report

**Comment by SilverRainZ** [comment]
#3 should work for you.

**Comment by SilverRainZ** [comment]
Try `==1.0.0b0`, see also: https://sphinx.silverrainz.me/comboroles/examples.html#cross-references-ref-doc-and-more

**Comment by diogo-rossi** [comment]
@SilverRainZ  Thanks for the quick reply!

It is working now!
